baseURL = "https://adage.usekarma.dev/"
title = "Adage"
theme = "hugo-book"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true


[params]
  BookTheme = "auto" # "light", "dark", or "auto"
  BookLogo = "assets/logo/adage_light_128x128.png"
  BookFavicon = "assets/logo/favicon-light.png"
  BookToC = true
  BookSection = "*"
  BookPostScript = "docs/inject-footer.html"
  BookPaletteLight = "adage-light"
  BookPaletteDark = "adage-dark"
  customCSS = ["assets/css/adage-light.css", "assets/css/adage-dark.css"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true  # Allows raw HTML in markdown
